In [1]:
import pandas as pd
import numpy as np

### Loading datasets

In [2]:
renewal_calls = pd.read_csv('../../data/raw/renewal_calls.csv')
billings = pd.read_csv('../../data/raw/billings.csv') 
cc_calls = pd.read_csv('../../data/raw/cc_calls.csv')
emails = pd.read_csv('../../data/raw/emails.csv')

C:\Users\AtharvaRana\AppData\Local\Temp\ipykernel_10892\1553648916.py:1: DtypeWarning: Columns (0: Churn_Category, 1: Complaint_Category, 2: Customer_Reaction_Category, 3: Agent_Renewal_Pitch_Category, 4: Customer_Renewal_Response_Category, 5: Agent_Response_Category, 6: Membership_Renewal_Decision, 7: Serious_Complaint, 8: Other_Complaint, 9: Discussion_on_Price_Increase, 10: Renewal_Impact_Due_to_Price_Increase, 11: Discount_or_Waiver_Requested, 12: Call_Reschedule_Request, 13: Agent_Flagged_Membership_Status_Alert, 14: Agent_Renewal_Initiation, 15: Explicit_Competitor_Mention, 16: Explicit_Switching_Intent, 17: Mentioned_Competitors, 18: Price_Switching_Mentioned, 19: Competitor_Value_Comparison, 20: Competitor_Benefits_Mentioned, 21: Topic_Introduced_By, 22: Percentage_Price_Increase_Mentioned, 23: Monetary_Price_Increase_Mentioned, 24: Price_Range_Mentioned, 25: Customer_Asked_For_Justification, 26: Customer_Response, 27: Desire_To_Cancel, 28: Discount_Offered, 29: Justification_Category, 30: Reason_For_Renewal_Category, 31: Agent_Response_To_Cancel_Category, 32: Argument_That_Convinced_Customer_to_Stay_Category) have mixed types. Specify dtype option on import or set low_memory=False.
  renewal_calls = pd.read_csv('../../data/raw/renewal_calls.csv')

C:\Users\AtharvaRana\AppData\Local\Temp\ipykernel_10892\1553648916.py:2: DtypeWarning: Columns (0: Proforma_Auto_Renewal, 1: Proforma_World_Pay_Token, 2: Current_Anchor_List, 3: Last_Renewal, 4: Last_Band) have mixed types. Specify dtype option on import or set low_memory=False.
  billings = pd.read_csv('../../data/raw/billings.csv')

C:\Users\AtharvaRana\AppData\Local\Temp\ipykernel_10892\1553648916.py:4: DtypeWarning: Columns (0: crm_agent_chase_count, 1: crm_auto_renewal_status) have mixed types. Specify dtype option on import or set low_memory=False.
  emails = pd.read_csv('../../data/raw/emails.csv')

Exploring renewal_calls

In [3]:
renewal_calls.shape

(186534, 41)

In [4]:
renewal_calls.head()

,Call_ID,Call_Direction,Co_Ref,Call_Date,Churn_Category,Complaint_Category,Customer_Reaction_Category,Agent_Renewal_Pitch_Category,Customer_Renewal_Response_Category,Agent_Response_Category,...,Customer_Response,Desire_To_Cancel,Discount_Offered,Justification_Category,Reason_For_Renewal_Category,Agent_Response_To_Cancel_Category,Argument_That_Convinced_Customer_to_Stay_Category,Analysed_Call,Call_Number,Call_Year
0,5.950000e+11,Outbound,UB0899,29-01-2025,NaN,NaN,Not Mentioned,Discussion / Introduction / Inquiry,Discount and Offer,Discount and Offer,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,3,2025
1,5.970000e+11,OUT_BOUND,HN5141,26-02-2025,NaN,NaN,NaN,Price and Cost,Agreement,Customer Communication,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,2,2025
2,5.950000e+11,Outbound,BP5009,24-01-2025,NaN,NaN,NaN,Expiration / Due,Agreement,Accreditation and Certification,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,1,2025
3,6.520000e+11,OUT_BOUND,XP8119,09-06-2025,NaN,NaN,NaN,Auto / Automatic,Agreement,Accreditation and Certification,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,1,2025
4,5.370000e+11,Outbound,ZL7978,20-08-2024,NaN,NaN,NaN,NaN,NaN,NaN,...,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,28,2024

In [5]:
renewal_calls.info()

<class 'pandas.DataFrame'>
RangeIndex: 186534 entries, 0 to 186533
Data columns (total 41 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   Call_ID                                            186534 non-null  float64
 1   Call_Direction                                     186534 non-null  str
 2   Co_Ref                                             179149 non-null  str
 3   Call_Date                                          186534 non-null  str
 4   Churn_Category                                     7902 non-null    str
 5   Complaint_Category                                 19008 non-null   str
 6   Customer_Reaction_Category                         23085 non-null   str
 7   Agent_Renewal_Pitch_Category                       53738 non-null   str
 8   Customer_Renewal_Response_Category                 54312 non-null   str
 9   Agent_Response_Category                            53980 non-null   str
 10  Membership_Renewal_Decision                        86574 non-null   str
 11  Serious_Complaint                                  84333 non-null   str
 12  Other_Complaint                                    84332 non-null   str
 13  Discussion_on_Price_Increase                       88034 non-null   str
 14  Renewal_Impact_Due_to_Price_Increase               88005 non-null   str
 15  Discount_or_Waiver_Requested                       88005 non-null   str
 16  Call_Reschedule_Request                            88578 non-null   str
 17  Agent_Flagged_Membership_Status_Alert              88578 non-null   str
 18  Agent_Renewal_Initiation                           88578 non-null   str
 19  Explicit_Competitor_Mention                        88704 non-null   str
 20  Unnamed: 20                                        0 non-null       float64
 21  Explicit_Switching_Intent                          88704 non-null   str
 22  Mentioned_Competitors                              88706 non-null   str
 23  Price_Switching_Mentioned                          88662 non-null   str
 24  Competitor_Value_Comparison                        88665 non-null   str
 25  Competitor_Benefits_Mentioned                      86578 non-null   str
 26  Topic_Introduced_By                                88721 non-null   str
 27  Percentage_Price_Increase_Mentioned                88721 non-null   str
 28  Monetary_Price_Increase_Mentioned                  88721 non-null   str
 29  Price_Range_Mentioned                              88721 non-null   str
 30  Customer_Asked_For_Justification                   88721 non-null   str
 31  Customer_Response                                  88721 non-null   str
 32  Desire_To_Cancel                                   88718 non-null   str
 33  Discount_Offered                                   88721 non-null   str
 34  Justification_Category                             13080 non-null   str
 35  Reason_For_Renewal_Category                        16135 non-null   str
 36  Agent_Response_To_Cancel_Category                  4927 non-null    str
 37  Argument_That_Convinced_Customer_to_Stay_Category  1818 non-null    str
 38  Analysed_Call                                      88744 non-null   float64
 39  Call_Number                                        186534 non-null  int64
 40  Call_Year                                          186534 non-null  int64
dtypes: float64(3), int64(2), str(36)
memory usage: 58.3 MB

In [6]:
renewal_calls.describe()

            Call_ID  Unnamed: 20  Analysed_Call    Call_Number      Call_Year
count  1.865340e+05          0.0        88744.0  186534.000000  186534.000000
mean   5.964301e+11          NaN            1.0     150.579926    2024.599070
std    7.543269e+10          NaN            0.0     824.314463       0.598115
min    1.930000e+11          NaN            1.0       1.000000    2024.000000
25%    5.130000e+11          NaN            1.0       2.000000    2024.000000
50%    5.950000e+11          NaN            1.0       4.000000    2025.000000
75%    6.790000e+11          NaN            1.0      10.000000    2025.000000
max    6.950000e+11          NaN            1.0    7313.000000    2026.000000

In [7]:
null_df = pd.DataFrame({
    'Null Count': renewal_calls.isnull().sum(),
    'Null %': round(renewal_calls.isnull().sum() / len(renewal_calls) * 100, 2)
})
null_df.sort_values('Null %', ascending=False)

                                                   Null Count  Null %
Unnamed: 20                                            186534  100.00
Argument_That_Convinced_Customer_to_Stay_Category      184716   99.03
Agent_Response_To_Cancel_Category                      181607   97.36
Churn_Category                                         178632   95.76
Justification_Category                                 173454   92.99
Reason_For_Renewal_Category                            170399   91.35
Complaint_Category                                     167526   89.81
Customer_Reaction_Category                             163449   87.62
Agent_Renewal_Pitch_Category                           132796   71.19
Agent_Response_Category                                132554   71.06
Customer_Renewal_Response_Category                     132222   70.88
Other_Complaint                                        102202   54.79
Serious_Complaint                                      102201   54.79
Membership_Renewal_Decision                             99960   53.59
Competitor_Benefits_Mentioned                           99956   53.59
Discount_or_Waiver_Requested                            98529   52.82
Renewal_Impact_Due_to_Price_Increase                    98529   52.82
Discussion_on_Price_Increase                            98500   52.81
Call_Reschedule_Request                                 97956   52.51
Agent_Renewal_Initiation                                97956   52.51
Agent_Flagged_Membership_Status_Alert                   97956   52.51
Competitor_Value_Comparison                             97869   52.47
Price_Switching_Mentioned                               97872   52.47
Explicit_Competitor_Mention                             97830   52.45
Mentioned_Competitors                                   97828   52.45
Explicit_Switching_Intent                               97830   52.45
Customer_Response                                       97813   52.44
Customer_Asked_For_Justification                        97813   52.44
Price_Range_Mentioned                                   97813   52.44
Desire_To_Cancel                                        97816   52.44
Topic_Introduced_By                                     97813   52.44
Percentage_Price_Increase_Mentioned                     97813   52.44
Monetary_Price_Increase_Mentioned                       97813   52.44
Discount_Offered                                        97813   52.44
Analysed_Call                                           97790   52.42
Co_Ref                                                   7385    3.96
Call_ID                                                     0    0.00
Call_Direction                                              0    0.00
Call_Date                                                   0    0.00
Call_Number                                                 0    0.00
Call_Year                                                   0    0.00

In [8]:
renewal_calls.nunique()

Call_ID                                                 53
Call_Direction                                           4
Co_Ref                                               36303
Call_Date                                              467
Churn_Category                                          18
Complaint_Category                                      22
Customer_Reaction_Category                              13
Agent_Renewal_Pitch_Category                            18
Customer_Renewal_Response_Category                      20
Agent_Response_Category                                 20
Membership_Renewal_Decision                              3
Serious_Complaint                                        3
Other_Complaint                                          4
Discussion_on_Price_Increase                             4
Renewal_Impact_Due_to_Price_Increase                    21
Discount_or_Waiver_Requested                            33
Call_Reschedule_Request                                  3
Agent_Flagged_Membership_Status_Alert                    3
Agent_Renewal_Initiation                                 3
Explicit_Competitor_Mention                              6
Unnamed: 20                                              0
Explicit_Switching_Intent                                8
Mentioned_Competitors                                   11
Price_Switching_Mentioned                                6
Competitor_Value_Comparison                             82
Competitor_Benefits_Mentioned                          350
Topic_Introduced_By                                      3
Percentage_Price_Increase_Mentioned                      3
Monetary_Price_Increase_Mentioned                        3
Price_Range_Mentioned                                 3107
Customer_Asked_For_Justification                         3
Customer_Response                                        4
Desire_To_Cancel                                       474
Discount_Offered                                         3
Justification_Category                                  30
Reason_For_Renewal_Category                             23
Agent_Response_To_Cancel_Category                       22
Argument_That_Convinced_Customer_to_Stay_Category       17
Analysed_Call                                            1
Call_Number                                            638
Call_Year                                                3
dtype: int64

In [9]:
renewal_calls.duplicated().sum()

np.int64(28812)

In [10]:
renewal_calls['Call_Direction'].value_counts(dropna=False)

Call_Direction
Outbound     83493
OUT_BOUND    77719
IN_BOUND     12731
Inbound      12591
Name: count, dtype: int64

In [11]:
renewal_calls['Churn_Category'].value_counts(dropna=False)

Churn_Category
NaN                                        178632
Unnecessary / Not needed                     1689
Cost / Price / Too expensive                 1527
Financial struggles / Business Problems       948
Left / Not with client anymore                811
Not Mentioned                                 588
Lack of Benefits                              529
Accreditation / Certification                 335
Switch / Change / Alternate Provider          289
Customer Service / Support                    233
Payment / Invoice Issue                       207
Client Requirement                            196
Process Issues                                154
Account Information                           117
Others                                         87
Auto / Automatic                               74
Value of service                               67
Portal / Technical Issues                      27
Audit                                          24
Name: count, dtype: int64

Exploring billings

In [12]:
billings.head()

,Co_Ref,Renewal_Month,Connection_Net,Connection_Qty,Discount_Amount,Sustainability_Score,Total_Renewal_Score_New,Starting_Connection_Net,Starting_Connection_Qty,Last_Years_Price,...,Connection_Group,Tenure_Group,#_of_Connection,Last_Renewal,Last_Band,Last_Total_Net_Paid,Last_Connections,Anchor_Group,Renewal_Year,DateTime_Out
0,VT6174,01-11-2024,NaN,NaN,NaN,8.0,42.5,NaN,NaN,799.0,...,1,3,1.0,01-11-2023,Band B,664.0,1.0,1,2024,01-11-2024
1,VD3828,01-08-2025,NaN,NaN,NaN,8.0,41.5,NaN,NaN,799.0,...,1,1,1.0,NaN,NaN,NaN,NaN,1,2025,01-08-2025
2,DV8120,01-03-2025,NaN,NaN,NaN,8.0,33.0,NaN,NaN,799.0,...,1,4+,1.0,01-03-2024,Band C1,749.0,1.0,1,2025,01-03-2025
3,EZ9894,01-06-2025,NaN,NaN,NaN,9.5,44.5,NaN,NaN,799.0,...,1,4+,1.0,01-06-2024,Band C1,749.0,1.0,1,2025,01-06-2025
4,FA8957,01-03-2025,NaN,NaN,NaN,9.5,42.5,NaN,NaN,799.0,...,1,3,1.0,01-03-2024,Band C1,749.0,1.0,1,2025,01-03-2025

In [13]:
billings.info()

<class 'pandas.DataFrame'>
RangeIndex: 122082 entries, 0 to 122081
Data columns (total 59 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Co_Ref                      122082 non-null  str
 1   Renewal_Month               122082 non-null  str
 2   Connection_Net              8037 non-null    float64
 3   Connection_Qty              8037 non-null    float64
 4   Discount_Amount             13551 non-null   str
 5   Sustainability_Score        122082 non-null  float64
 6   Total_Renewal_Score_New     122082 non-null  float64
 7   Starting_Connection_Net     8545 non-null    float64
 8   Starting_Connection_Qty     8545 non-null    float64
 9   Last_Years_Price            112992 non-null  float64
 10  Last_Years_Date_Paid        0 non-null       float64
 11  Auto_Renewal_Score          122082 non-null  int64
 12  Status_Scores               122082 non-null  int64
 13  Anchoring_Score             122082 non-null  float64
 14  Tenure_Scores               122082 non-null  float64
 15  Proforma_Auto_Renewal       104030 non-null  object
 16  Proforma_World_Pay_Token    104030 non-null  object
 17  Proforma_Date               121778 non-null  str
 18  Current_Anchorings          122082 non-null  int64
 19  Current_Anchor_List         96125 non-null   str
 20  Payment_Timeframe           101226 non-null  float64
 21  Registration_Date           121064 non-null  str
 22  Proforma_Account_Stage      112853 non-null  str
 23  Proforma_Audit_Status       112853 non-null  str
 24  Current_Auto_Renewal_Flag   122082 non-null  str
 25  Current_World_Pay_Token     122082 non-null  str
 26  Renewal_Score_At_Release    121956 non-null  float64
 27  Proforma_Membership_Status  121956 non-null  str
 28  Proforma_Approved_Lists     121956 non-null  float64
 29  Tenure_Years                121064 non-null  float64
 30  Band                        122058 non-null  str
 31  Prospect_Renewal_Date       122082 non-null  str
 32  Closed_Date                 113894 non-null  str
 33  Prospect_Status             122082 non-null  str
 34  Starting_Net                122082 non-null  int64
 35  Starting_Vat                122082 non-null  float64
 36  Starting_Gross              122082 non-null  float64
 37  Starting_Membership_Net     122082 non-null  int64
 38  Starting_Package_Net        122082 non-null  int64
 39  Starting_PQQ_Net            122082 non-null  int64
 40  Gross                       122082 non-null  float64
 41  Membership_Net              122082 non-null  float64
 42  Package_Net                 122082 non-null  float64
 43  PQQNet                      122082 non-null  int64
 44  Total_Net_Paid              101226 non-null  float64
 45  Prospect_Outcome            122082 non-null  str
 46  Payment_Method              122082 non-null  str
 47  Amount                      122082 non-null  int64
 48  Total_Amount                122082 non-null  float64
 49  Connection_Group            121956 non-null  str
 50  Tenure_Group                121064 non-null  str
 51  #_of_Connection             121956 non-null  float64
 52  Last_Renewal                73791 non-null   str
 53  Last_Band                   73771 non-null   str
 54  Last_Total_Net_Paid         73726 non-null   float64
 55  Last_Connections            73702 non-null   float64
 56  Anchor_Group                121956 non-null  str
 57  Renewal_Year                122082 non-null  int64
 58  DateTime_Out                122082 non-null  str
dtypes: float64(24), int64(10), object(2), str(23)
memory usage: 55.0+ MB

In [14]:
billings.describe()

,Connection_Net,Connection_Qty,Sustainability_Score,Total_Renewal_Score_New,Starting_Connection_Net,Starting_Connection_Qty,Last_Years_Price,Last_Years_Date_Paid,Auto_Renewal_Score,Status_Scores,...,Membership_Net,Package_Net,PQQNet,Total_Net_Paid,Amount,Total_Amount,#_of_Connection,Last_Total_Net_Paid,Last_Connections,Renewal_Year
count,8037.000000,8037.000000,122082.000000,122082.000000,8545.000000,8545.000000,112992.000000,0.0,122082.000000,122082.000000,...,122082.000000,122082.000000,122082.000000,101226.000000,122082.000000,122082.000000,121956.000000,73726.000000,73702.000000,122082.000000
mean,418.268259,5.799925,8.619530,41.983319,463.591223,6.419310,1063.854763,NaN,8.479506,7.187685,...,848.107740,60.233556,133.188996,1077.907507,1107.750864,1069.066063,3.198670,993.923497,3.547773,2024.300290
std,623.568386,7.608354,0.692765,4.291603,685.366345,8.401839,694.584676,NaN,0.499582,3.263780,...,533.440504,67.069747,48.608783,651.303068,689.139920,675.506405,6.548384,518.252054,6.951354,1.029394
min,55.000000,1.000000,8.000000,30.500000,55.000000,1.000000,0.000000,NaN,8.000000,0.000000,...,0.000000,0.000000,-529.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2023.000000
25%,99.000000,1.000000,8.000000,41.500000,110.000000,2.000000,664.000000,NaN,8.000000,7.000000,...,500.000000,0.000000,99.000000,684.000000,699.000000,684.000000,1.000000,684.000000,1.000000,2023.000000
50%,220.000000,3.000000,8.000000,43.500000,225.000000,3.000000,919.000000,NaN,8.000000,9.000000,...,674.000000,0.000000,135.000000,924.000000,934.000000,919.000000,1.000000,869.000000,2.000000,2024.000000
75%,474.000000,7.000000,9.500000,45.000000,495.000000,7.000000,1264.000000,NaN,9.000000,9.000000,...,1014.000000,120.000000,135.000000,1269.000000,1274.000000,1239.000000,3.000000,1149.000000,4.000000,2025.000000
max,4752.000000,48.000000,9.500000,46.500000,4752.000000,48.000000,18326.000000,NaN,9.000000,9.000000,...,13245.000000,225.000000,1930.000000,18326.000000,19927.000000,18326.000000,197.000000,12616.000000,197.000000,2050.000000

In [15]:
null_df_b = pd.DataFrame({
    'Null Count': billings.isnull().sum(),
    'Null %': round(billings.isnull().sum() / len(billings) * 100, 2)
})
null_df_b.sort_values('Null %', ascending=False)

                            Null Count  Null %
Last_Years_Date_Paid            122082  100.00
Connection_Qty                  114045   93.42
Connection_Net                  114045   93.42
Starting_Connection_Net         113537   93.00
Starting_Connection_Qty         113537   93.00
Discount_Amount                 108531   88.90
Last_Connections                 48380   39.63
Last_Total_Net_Paid              48356   39.61
Last_Band                        48311   39.57
Last_Renewal                     48291   39.56
Current_Anchor_List              25957   21.26
Payment_Timeframe                20856   17.08
Total_Net_Paid                   20856   17.08
Proforma_Auto_Renewal            18052   14.79
Proforma_World_Pay_Token         18052   14.79
Proforma_Account_Stage            9229    7.56
Proforma_Audit_Status             9229    7.56
Last_Years_Price                  9090    7.45
Closed_Date                       8188    6.71
Tenure_Years                      1018    0.83
Tenure_Group                      1018    0.83
Registration_Date                 1018    0.83
Proforma_Date                      304    0.25
Renewal_Score_At_Release           126    0.10
Proforma_Approved_Lists            126    0.10
Connection_Group                   126    0.10
#_of_Connection                    126    0.10
Anchor_Group                       126    0.10
Proforma_Membership_Status         126    0.10
Band                                24    0.02
Status_Scores                        0    0.00
Current_World_Pay_Token              0    0.00
Current_Auto_Renewal_Flag            0    0.00
Current_Anchorings                   0    0.00
Sustainability_Score                 0    0.00
Renewal_Month                        0    0.00
Co_Ref                               0    0.00
Total_Renewal_Score_New              0    0.00
Auto_Renewal_Score                   0    0.00
Tenure_Scores                        0    0.00
Anchoring_Score                      0    0.00
Prospect_Status                      0    0.00
Prospect_Renewal_Date                0    0.00
Package_Net                          0    0.00
Membership_Net                       0    0.00
Gross                                0    0.00
Starting_PQQ_Net                     0    0.00
Starting_Package_Net                 0    0.00
Starting_Membership_Net              0    0.00
Starting_Gross                       0    0.00
Starting_Vat                         0    0.00
Starting_Net                         0    0.00
Amount                               0    0.00
Prospect_Outcome                     0    0.00
Payment_Method                       0    0.00
PQQNet                               0    0.00
Total_Amount                         0    0.00
Renewal_Year                         0    0.00
DateTime_Out                         0    0.00

In [16]:
billings.duplicated().sum()

np.int64(0)

In [17]:
billings['Prospect_Outcome'].value_counts()

Prospect_Outcome
Won        101226
Churned     12668
Open         8188
Name: count, dtype: int64

Exploring cc_calls

In [18]:
cc_calls.head()

,Contact_ID,Call_Date,Direction,cc_care_package,cc_care_package_discussed,cc_urgency_getting_on_site,cc_external_consultant,cc_agent_cross_sell_attempt,cc_customer_issues_concerns,cc_business_struggles_financial_hardship,...,cc_contractor_sentiment_overall_score,cc_contractor_sentiment_issues_score,cc_pricing_mentioned,cc_pricing_sentiment_impact,cc_refund_discussed,cc_contractor_suggest_leave,cc_contractor_complained,Co_Ref,Analysed_Call,Call_Year
0,6.255130e+11,08-05-2025,OUT_BOUND,Standard,Yes,No,No,No,Yes,Yes,...,30,20,Yes,Yes,No,Yes,Yes,HV3323,1,2025
1,5.910870e+11,25-11-2024,OUT_BOUND,Standard,Yes,No,No,No,Yes,No,...,0,0,Yes,Yes,No,Yes,Yes,PJ7066,1,2024
2,5.650910e+11,23-10-2024,IN_BOUND,Standard,Yes,No,No,No,Yes,No,...,40,20,Yes,Yes,No,Yes,Yes,DP6030,1,2024
3,5.939750e+11,13-01-2025,IN_BOUND,Premier,Yes,No,No,No,Yes,Yes,...,40,30,Yes,Yes,Yes,Yes,Yes,AM2413,1,2025
4,6.222820e+11,19-03-2025,IN_BOUND,Standard,Yes,No,No,No,Yes,Yes,...,40,20,Yes,Yes,No,Yes,Yes,ED6707,1,2025

In [19]:
cc_calls.info()

<class 'pandas.DataFrame'>
RangeIndex: 32882 entries, 0 to 32881
Data columns (total 33 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Contact_ID                                32882 non-null  float64
 1   Call_Date                                 32882 non-null  str
 2   Direction                                 32882 non-null  str
 3   cc_care_package                           32744 non-null  str
 4   cc_care_package_discussed                 32744 non-null  str
 5   cc_urgency_getting_on_site                32744 non-null  str
 6   cc_external_consultant                    32744 non-null  str
 7   cc_agent_cross_sell_attempt               32744 non-null  str
 8   cc_customer_issues_concerns               32744 non-null  str
 9   cc_business_struggles_financial_hardship  32744 non-null  str
 10  cc_call_initiated_by                      32744 non-null  str
 11  cc_questionnaire_completion               32850 non-null  str
 12  cc_chasing_response                       32850 non-null  str
 13  cc_issues_within_questionnaire            32416 non-null  str
 14  cc_login_issues                           32849 non-null  str
 15  cc_platform_issues                        32849 non-null  str
 16  cc_dissatisfaction_time_to_complete       32849 non-null  str
 17  cc_process_complexity_concerns            32844 non-null  str
 18  cc_questions_harder_than_expected         32845 non-null  str
 19  cc_dissatisfaction_support                32846 non-null  str
 20  cc_contractor_sentiment                   32787 non-null  str
 21  cc_contractor_sentiment_start_score       32787 non-null  str
 22  cc_contractor_sentiment_end_score         32787 non-null  str
 23  cc_contractor_sentiment_overall_score     32787 non-null  str
 24  cc_contractor_sentiment_issues_score      32787 non-null  str
 25  cc_pricing_mentioned                      32787 non-null  str
 26  cc_pricing_sentiment_impact               32787 non-null  str
 27  cc_refund_discussed                       32787 non-null  str
 28  cc_contractor_suggest_leave               32787 non-null  str
 29  cc_contractor_complained                  32787 non-null  str
 30  Co_Ref                                    31686 non-null  str
 31  Analysed_Call                             32882 non-null  int64
 32  Call_Year                                 32882 non-null  int64
dtypes: float64(1), int64(2), str(30)
memory usage: 8.3 MB

In [20]:
null_df_c = pd.DataFrame({
    'Null Count': cc_calls.isnull().sum(),
    'Null %': round(cc_calls.isnull().sum() / len(cc_calls) * 100, 2)
})
null_df_c.sort_values('Null %', ascending=False)

                                          Null Count  Null %
Co_Ref                                          1196    3.64
cc_issues_within_questionnaire                   466    1.42
cc_call_initiated_by                             138    0.42
cc_external_consultant                           138    0.42
cc_care_package_discussed                        138    0.42
cc_agent_cross_sell_attempt                      138    0.42
cc_customer_issues_concerns                      138    0.42
cc_business_struggles_financial_hardship         138    0.42
cc_care_package                                  138    0.42
cc_urgency_getting_on_site                       138    0.42
cc_contractor_suggest_leave                       95    0.29
cc_refund_discussed                               95    0.29
cc_pricing_mentioned                              95    0.29
cc_contractor_sentiment_overall_score             95    0.29
cc_contractor_sentiment_end_score                 95    0.29
cc_contractor_sentiment                           95    0.29
cc_contractor_sentiment_issues_score              95    0.29
cc_pricing_sentiment_impact                       95    0.29
cc_contractor_complained                          95    0.29
cc_contractor_sentiment_start_score               95    0.29
cc_process_complexity_concerns                    38    0.12
cc_dissatisfaction_support                        36    0.11
cc_questions_harder_than_expected                 37    0.11
cc_questionnaire_completion                       32    0.10
cc_login_issues                                   33    0.10
cc_dissatisfaction_time_to_complete               33    0.10
cc_chasing_response                               32    0.10
cc_platform_issues                                33    0.10
Contact_ID                                         0    0.00
Call_Date                                          0    0.00
Direction                                          0    0.00
Analysed_Call                                      0    0.00
Call_Year                                          0    0.00

In [21]:
cc_calls.duplicated().sum()

np.int64(93)

Exploring emails

In [22]:
emails.head()

,Co_Ref,Time_to_Renewal,crm_accreditation_completed,crm_timely_completion,crm_progress_towards_accreditation,crm_delays_in_accreditation,crm_contractor_suggested_leave,crm_contractor_engagement,crm_contractor_sentiment,crm_contractor_sentiment_score,...,crm_accreditation_issues,crm_membership_overdue,crm_auto_renewal_status,crm_dissatisified_with_renewal_price,crm_customer_complained,crm_refund_mentioned,crm_negative_customer_experience,crm_dissatisfaction_with_support,crm_financial_hardship_mentioned,year
0,KG5766,pre_renewal,Not Discussed,Not Discussed,Not Discussed,Yes,No,Yes,Neutral,50,...,Not Discussed,Yes,0,No,No,Yes,Yes,No,Yes,2025
1,EJ1532,14_out,Not Discussed,Not Discussed,Not Discussed,No,Not Discussed,No,Not Discussed,Not Discussed,...,Not Discussed,Not Discussed,0,Not Discussed,No,Yes,Yes,No,Not Discussed,2025
2,AA4063,prior_year,Not Discussed,Not Discussed,Not Discussed,No,No,Yes,Neutral,50,...,Not Discussed,No,0,No,No,Yes,Yes,Yes,Not Discussed,2025
3,JY9888,prior_year,No,No,Not Discussed,Yes,No,Yes,Satisfied,80,...,Not Discussed,Yes,0,Not Discussed,No,Yes,Yes,No,Not Discussed,2025
4,WO6689,pre_renewal,Not Discussed,Not Discussed,Not Discussed,No,No,Yes,Satisfied,80,...,No,No,0,No,No,Yes,Yes,No,Not Discussed,2026

In [23]:
emails.info()

<class 'pandas.DataFrame'>
RangeIndex: 123389 entries, 0 to 123388
Data columns (total 27 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Co_Ref                                123389 non-null  str
 1   Time_to_Renewal                       123389 non-null  str
 2   crm_accreditation_completed           102354 non-null  str
 3   crm_timely_completion                 102354 non-null  str
 4   crm_progress_towards_accreditation    102354 non-null  str
 5   crm_delays_in_accreditation           102354 non-null  str
 6   crm_contractor_suggested_leave        102354 non-null  str
 7   crm_contractor_engagement             102354 non-null  str
 8   crm_contractor_sentiment              102354 non-null  str
 9   crm_contractor_sentiment_score        102354 non-null  str
 10  crm_dts_or_ssip_mentioned             102354 non-null  str
 11  crm_customer_payment_intention        102354 non-null  str
 12  crm_competitors_mentioned             112234 non-null  str
 13  crm_membership_level                  112234 non-null  str
 14  crm_platform_issues_raised            112234 non-null  str
 15  crm_agent_chased_contractor           112234 non-null  str
 16  crm_agent_chase_count                 112234 non-null  object
 17  crm_accreditation_issues              112234 non-null  str
 18  crm_membership_overdue                112234 non-null  str
 19  crm_auto_renewal_status               112234 non-null  object
 20  crm_dissatisified_with_renewal_price  112234 non-null  str
 21  crm_customer_complained               111914 non-null  str
 22  crm_refund_mentioned                  111914 non-null  str
 23  crm_negative_customer_experience      111914 non-null  str
 24  crm_dissatisfaction_with_support      111914 non-null  str
 25  crm_financial_hardship_mentioned      111914 non-null  str
 26  year                                  123389 non-null  int64
dtypes: int64(1), object(2), str(24)
memory usage: 25.4+ MB

In [24]:
null_df_e = pd.DataFrame({
    'Null Count': emails.isnull().sum(),
    'Null %': round(emails.isnull().sum() / len(emails) * 100, 2)
})
null_df_e.sort_values('Null %', ascending=False)

                                      Null Count  Null %
crm_accreditation_completed                21035   17.05
crm_progress_towards_accreditation         21035   17.05
crm_timely_completion                      21035   17.05
crm_contractor_engagement                  21035   17.05
crm_contractor_sentiment                   21035   17.05
crm_delays_in_accreditation                21035   17.05
crm_contractor_suggested_leave             21035   17.05
crm_contractor_sentiment_score             21035   17.05
crm_dts_or_ssip_mentioned                  21035   17.05
crm_customer_payment_intention             21035   17.05
crm_dissatisfaction_with_support           11475    9.30
crm_negative_customer_experience           11475    9.30
crm_refund_mentioned                       11475    9.30
crm_customer_complained                    11475    9.30
crm_financial_hardship_mentioned           11475    9.30
crm_membership_overdue                     11155    9.04
crm_accreditation_issues                   11155    9.04
crm_membership_level                       11155    9.04
crm_competitors_mentioned                  11155    9.04
crm_platform_issues_raised                 11155    9.04
crm_dissatisified_with_renewal_price       11155    9.04
crm_agent_chase_count                      11155    9.04
crm_agent_chased_contractor                11155    9.04
crm_auto_renewal_status                    11155    9.04
Time_to_Renewal                                0    0.00
Co_Ref                                         0    0.00
year                                           0    0.00

In [25]:
emails.duplicated().sum()

np.int64(0)

In [26]:
emails['Time_to_Renewal'].value_counts()

Time_to_Renewal
prior_year     40022
14_out         32493
45_out         28008
pre_renewal    22866
Name: count, dtype: int64